### ISSUE TITLE
Password Reset Crashes on Bogus Address

### ISSUE THREAD

**Issue by excalq** [Apogaea/voldb#121]
I see the following error when I try to reset an email address not actually registered to an account.

![image](https://cloud.githubusercontent.com/assets/610274/6890646/9eda8cee-d66c-11e4-9902-19e03143bc86.png)

I dug into the code (dev branch) to see if it's anything I can fix, however it seems this is internal to `django-authtools` (?) so I didn't get far.

**Comment by pipermerriam** [comment]
Fixed in https://github.com/Apogaea/voldb/pull/122
