### ISSUE TITLE
Failed Delete - "CSRF verification failed. Request aborted."

### ISSUE THREAD

**Issue by Zaskoda** [Apogaea/voldb#144]
I entered a shift wrong and needed to delete it. The confirmation on delete took me to this uri:

http://volunteer.apogaea.com/admin/departments/65/roles/86/shifts/2062/delete/

The page generated an error. I've attached a screen capture of the error. The shift does not appear to be deleted. 
![forbidden](https://cloud.githubusercontent.com/assets/611731/7082491/4c7defc6-df0a-11e4-8471-2b529536461a.png)

**Comment by pipermerriam** [comment]
Fixed, deploy going out soon.
