### ISSUE TITLE
Shifts need multiplyers.

### ISSUE THREAD

**Issue by Zaskoda** [Apogaea/voldb#46]
Both of the leaderboard and for departmental planning, we often want to make a shift "worth more". The most straight forward approach to solve this problem could be creating a "multiplier". This multiplier should be visible on the shifts page, but not alter the perception of how many hours that shift requires. (perhaps an "x3" type tag in the corner of the shift). The multiplier should be used on the leaderboard to calculate a total "score" (hours x multiplier = score).

Question: should the multiplier be a float or an int?

**Comment by pipermerriam** [comment]
Punting on this for now as leaderboards are going away (temporarily) with the new refactor.
