### ISSUE TITLE
Show current % of shifts filled.

### ISSUE THREAD

**Issue by Zaskoda** [Apogaea/voldb#54]
On the top of shift pages, we should be showing the % of the shifts that are filled and perhaps a countdown showing how many days there are until Apogaea opens.

**Comment by pipermerriam** [comment]
This sort of metadata is easy to display.

- Per department show % and `x / y` number of shifts filled.
- Per role show % and `x / y` number of shifts filled.
- In site header, show global % and `x / y` number of shifts filled.
