### ISSUE TITLE
How can the client submit changes to the server?

### ISSUE THREAD

**Issue by devnill** [Apogaea/voldb#84]
I'm working on shift signup and release functionality. For these changes to be meaningful, we will have to submit the changed objects to the server. 

Are these endpoints set up yet? If not, do you have a preference on how I should submit changes?

**Comment by devnill** [comment]
Perfect.

**Comment by devnill** [comment]
I modified it slightly, so instead of /shifts/:shiftID/claim, I post the model back to /shifts/:shiftID/. This will transfer the claiming User ID as well as any other data that the client may have about the shift.

We still need to talk about auth since i'm not passing any token in the header to verify who is actually making the claim.

**Comment by pipermerriam** [comment]
> We still need to talk about auth since i'm not passing any token in the header to verify who is actually making the claim.

Auth won't need any code on your side.  Current plan is to stick with session based authentication so the cookies the user has in the browser will identify them with the server.

You will need to [implement csrf protection for the xhr requests you make](https://docs.djangoproject.com/en/1.7/ref/contrib/csrf/#ajax)

**Comment by pipermerriam** [comment]
This has been redone in current refactor.
