### ISSUE TITLE
Admin Crashes on User Save

### ISSUE THREAD

**Issue by excalq** [Apogaea/voldb#89]
I have only the superuser existing, and am trying to add a second user via /admin.
I'm using the SQLite DB. Probably something obvious...?

This happens on the `django_integration` branch, unsure of others.

![screenshot 2015-03-10 21 30 59](https://cloud.githubusercontent.com/assets/610274/6590417/d52e966e-c76c-11e4-91c0-640aad33399e.png)

**Comment by pipermerriam** [comment]
Django based admin is going away with the work i'm doing.
